spring:
  datasource:
    url: jdbc:mysql://glorylogdb.cxoss2ksihqk.ap-northeast-2.rds.amazonaws.com:3306/glorylogdb
    username: root
    password: 57138365
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

  data:
    web:
      pageable:
        one-indexed-parameters: true
        #1부터 시작을 하겠다 기본 값이 false -> 0부터 시작하겠다.
        default-page-size: 5

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create
        dialect: org.hibernate.dialect.MySQLDialect
        # show_sql: true
        format_sql: true
    defer-datasource-initialization: ture

logging.level:
  org.hibernate.SQL: debug

glory:
  jwt-Key: "A7CHmMZ/yELDqzbAGac4105ftkVsVHIxF2ad4oywpiQ="



