spring:
  datasource:
    url: jdbc:mysql://glorylogdb.cxoss2ksihqk.ap-northeast-2.rds.amazonaws.com:3306/glorylogdb
    username: root
    password: 57138365
    driver-class-name: com.mysql.cj.jdbc.Driver

  output:
    ansi:
      enabled: always

  data:
    web:
      pageable:
        max-page-size: 2000
        default-page-size: 20
        one-indexed-parameters: true

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create
        dialect: org.hibernate.dialect.MySQLDialect
        # show_sql: true
        format_sql: true
    defer-datasource-initialization: ture

logging.level:
  org.hibernate.SQL: debug




